### ISSUE TITLE
E: Package 'python3-mysqldb' has no installation candidate

### ISSUE THREAD

**Issue by shotsharpcrack** [kevinwlu/iot#1]
**pi@raspberrypi:~ $ sudo apt-get install python3-mysqldb**
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package python3-mysqldb is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3-mysqldb' has no installation candidate

**pi@raspberrypi:~ $ sudo easy_install pymysql
pi@raspberrypi:~ $ cd stevens
pi@raspberrypi:~/stevens $ sudo nano manage.py**

add: 
**import pymysql
pymysql.install_as_MySQLdb()**

**Comment by kevinwlu** [comment]
pi@iotus:~ $ sudo apt-get install python3-mysqldb
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Suggested packages:
  python-egenix-mxdatetime python3-mysqldb-dbg
The following NEW packages will be installed:
  python3-mysqldb
0 upgraded, 1 newly installed, 0 to remove and 41 not upgraded.
Need to get 45.8 kB of archives.
After this operation, 150 kB of additional disk space will be used.
Get:1 http://raspbian.mirror.constant.com/raspbian stretch/main armhf python3-mysqldb armhf 1.3.7-1.1 [45.8 kB]
Fetched 45.8 kB in 0s (134 kB/s)         
Selecting previously unselected package python3-mysqldb.
(Reading database ... 143852 files and directories currently installed.)
Preparing to unpack .../python3-mysqldb_1.3.7-1.1_armhf.deb ...
Unpacking python3-mysqldb (1.3.7-1.1) ...
Setting up python3-mysqldb (1.3.7-1.1) ...
pi@iotus:~ $
